{
"Welcome to Tripvia",
"Book Via Travel for my trip",
"Pickup City",
"Destination City",
"Date",
"Passengers",
"Search Travel",
"Advertise with our partners",
"ViaAds running ads",
"View Ad Offers",
"Transaction",
"Process",
"Completed",
"Cancel",
"Number of tickets",
"Date",
"Departure",
"Buyer Name",
"Status",
"Paid",
"Pending",
"Unpaid",
"Pickup",
"Seat Details",
"Description",
"Available",
"Already occupied",
"Selected",
"e-ticket",
"Customer",
"Account Settings",
"Manage Profile",
"Full Name",
"WhatsApp Number",
"Save",
"Terms and Conditions",
"Privacy Policy",
"Exit Application";
"Register",
"WhatsApp Number",
"Enter WhatsApp Number",
"Login",
"Don't have an account? Register",
"Notification",
"Order successfully paid!",
"Order expired",
"Pickup Location",
"Return",
"Payment Details",
"Pay Before",
"Invoice",
"Order Fee",
"Admin Fee",
"Total Fee",
"Payment Account Name",
"Check Payment Status",
"Scan QR Code Below",
"No time limit",
"Virtual Account Number",
"Copy";
}