{
  "Selamat datang di Tripvia",
    "Pesan Via Travel untuk perjalanan saya",
    "Kota Penjemputan",
    "Kota Tujuan",
    "Tanggal",
    "Penumpang",
    "Cari Travel",
    "Beriklan dengan mitra kami",
    "Melalui iklan berjalan ViaAds",
    "Lihat Penawaran Iklan",
    "Transaksi",
    "Proses",
    "Selesai",
    "Batal",
    "Jumlah tiket",
    "Tanggal",
    "Keberangkatan",
    "Nama Pembeli",
    "Status",
    "Dibayar",
    "Tertunda",
    "Belum dibayar",
    "Penjemputan",
    "Detail Kursi",
    "Keterangan",
    "Tersedia",
    "Sudah terisi",
    "Dipilih",
    "e-tiket",
    "Customer",
    "Pengaturan Akun",
    "Atur Profile",
    "Nama Lengkap",
    "No. Whatsapp",
    "Simpan",
    "Syarat dan Ketentuan",
    "Kebijakan Privasi",
    "Keluar Aplikasi";
  "Daftar",
    "No. Whatsapp",
    "Masukkan No. Whatsapp",
    "Masuk",
    "Belum punya akun? Daftar",
    "Pemberitahuan",
    "Pesanan sukses dibayar!",
    "Pesanan kedaluwarsa",
    "Lokasi Penjemputan",
    "Kembali",
    "Detail Pembayaran",
    "Bayar Sebelum",
    "Faktur",
    "Biaya Pemesanan",
    "Biaya admin",
    "Total Biaya",
    "Nama Akun Pembayaran",
    "Cek Status Pembayaran",
    "Scan Barcode Qris Berikut",
    "Tidak ada batas waktu",
    "Nomor Virtual Akun",
    "Salin";
}
